### ISSUE TITLE
Crashing if you run comments

### ISSUE THREAD

**Issue by jozephbrasil** [harrypython/itsagramlive#14]
**Describe the bug**
Crashing when using "comments" command.

**To Reproduce**
1. Start a live request
2. Run "mute comments"
3. Run comments
4. See error - crashing

**Expected behavior**
Should be notified: you are muted and there is no comments.

**Comment by jozephbrasil** [comment]
Still crashing...

command> mute comments
Comments muted
command> comments
Traceback (most recent call last):
  File "live_broadcast.py", line 5, in <module>
    live.start()
  File "\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ItsAGramLive\ItsAGramLive.py", line 231, in start
    self.get_comments()
  File "\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ItsAGramLive\ItsAGramLive.py", line 401, in get_comments
    for comment in self.LastJson['comments']:
KeyError: 'comments'
