### ISSUE TITLE
ItsAGramLive Support for Headless Server?

### ISSUE THREAD

**Issue by shelomito12** [harrypython/itsagramlive#26]
Is it possible to pass an option/command to the python script in order to omit Pyperclip since I want to run your project in a headless (Linux) VPS?

```
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 
```

Could it just print RTMP URL/KEY to standard output?

I'm interested in using your script with FFMPEG support: https://github.com/harrypython/itsagramlive/issues/4

**Comment by shelomito12** [comment]
Hey @harrypython , thanks for this wonderful python script. Do you have by any chance an ETA for updating the script with the above request? - Thanks in advance.

**Comment by harrypython** [comment]
@jzvi12
Try the 1.4.1 version

Thank you. 😊

**Comment by shelomito12** [comment]
@harrypython Thanks, it worked. I was able to get the stream key in the console output.

Now, from #4  ,  I created a similar script like yours:

```
import json
import subprocess

from ItsAGramLive import ItsAGramLive

FILE_PATH = "youtube.com/watch?v=XxxXXxxx"

#live = ItsAGramLive()
live = ItsAGramLive(username='github', password='test123')

broadcast_id = live.create_broadcast()

ffmpeg_cmd = """streamlink --hls-live-restart -o - '{file}' best | /home/ubuntu/ffmpeg-git/ffmpeg -re  -i pipe:0 -vf "transpose=1,pad=w=max(ih*4/5\,iw):h=ih:x=(iw-ow)/
2:y=(ih-oh/2):color=black,pad=w=iw:h=max(iw*9/16\,ih):x=(iw-ow)/2:y=(ih-oh/2):color=black" -preset ultrafast -c:v libx264 -pix_fmt yuv420p -crf 30 -b:v 1500k -maxrate 
1500k -bufsize 3000k -r 30 -c:a aac -ac 2 -b:a 128k -ar 44100 -g 60 -f flv  '{stream_url}'""" \
    .format(file=FILE_PATH, stream_url=live.LastJson['upload_url'])

data = json.dumps({'_uuid': live.uuid,
                   '_uid': live.username_id,
                   'should_send_notifications': int(live.sendNotification),
                   '_csrftoken': live.token})

if live.send_request(endpoint='live/' + str(broadcast_id) + '/start/', post=live.generate_signature(data)):

    print('CTRL+C to quit.')
    try:
        subprocess.call(ffmpeg_cmd, shell=True)
    except KeyboardInterrupt:
        pass
    except Exception as error:
        print(error)

    live.end_broadcast(broadcast_id)
```

But when I execute it I get the following exception:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    broadcast_id = live.create_broadcast()
  File "/home/ubuntu/itsagramlive/ItsAGramLive/ItsAGramLive.py", line 384, in create_broadcast
    if self.send_request(endpoint='live/create/', post=self.generate_signature(data)):
  File "/home/ubuntu/itsagramlive/ItsAGramLive/ItsAGramLive.py", line 169, in send_request
    raise Exception("Not logged in!\n")
Exception: Not logged in!
```
Any thoughts?

**Comment by harrypython** [comment]
I believe that at this point of the project (we change somethings after issue #4) a better strategy is run two different processes.

> FILE_PATH = "youtube.com/watch?v=XxxXXxxx"

Are you trying to stream a  youtube video? 🤨

**Comment by shelomito12** [comment]
> Are you trying to stream a youtube video? 🤨

for testing purposes, I use streamlink along with ffmpeg to stream a YT video to IG

**Comment by harrypython** [comment]
@jzvi12 check my last update on README.md
