### ISSUE TITLE
Problem finishing live

### ISSUE THREAD

**Issue by gotagautier** [harrypython/itsagramlive#34]
I use Itsagramlive for about 9 months now and work perfectly until a couple days ago.
Now when I finish a live (I use OBS) I type STOP in the command and then press the Y key to save the replay to IGTV or even the N key to not save anything but the CMD show me the following error:

* Except on SendRequest (wait 60 sec and resend): Expecting value: line 1 column 1 (char 0)
* ...
* and repeat the same lines after 60sec

when I press ctrl + C to finish the script it says the following lines

Traceback (most recent call last):
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 190, in send_request
    self.LastJson = json.loads(self.LastResponse.text)
  File "c:\Python3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\Python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python3\IG\test.py", line 11, in <module>
    live.start()
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 255, in start
    self.stop()
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 488, in stop
    self.delete_post_live()
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 473, in delete_post_live
    if self.send_request(endpoint='live/{}/delete_post_live/'.format(self.broadcast_id),
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 195, in send_request
    time.sleep(60)

Theres an update or something to fix this problem? 
Im an sound engineer and due to covid I cant work doing live and big concerts like I always do, so this my only job now and you really help me a lot with this script
Thanks for all your hard work!

**Comment by harrypython** [comment]
Hello again @gotagautier 
Check your previous issue #25

**Comment by harrypython** [comment]
Hey  @gotagautier
I'm so happy to hear about your work using my script.
Please, let me know if I can do anything else to help u.
