### ISSUE TITLE
Bad password

### ISSUE THREAD

**Issue by gotagautier** [harrypython/itsagramlive#39]
I just update to last version (1.4.3) and now send me a message for bad password. 
I start the same file with same password in all versions, if I return to 1.4.1 version it works fine
the error is the following lines:

Let's do it!
Traceback (most recent call last):
  File "c:\python3\IG\test.py", line 11, in <module>
    live.start()
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 241, in start
    if not self.login():
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 131, in login
    if self.LastJson['error_type'] == 'bad_password':
KeyError: 'error_type'

**Comment by harrypython** [comment]
Thank you so much for your alert

Please update to version 1.4.4 and give me your feedback

**Comment by gotagautier** [comment]
I have other error message now:

Traceback (most recent call last):
  File "c:\python3\IG\test.py", line 6, in <module>
    live = ItsAGramLive(
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 71, in __init__
    m.update(args.username.encode('utf-8') + args.password.encode('utf-8'))
UnboundLocalError: local variable 'args' referenced before assignment

Maybe I need change anything into my file settings?

**Comment by harrypython** [comment]
> Maybe I need change anything into my file settings?

No, I believe was my mistake. Can you tray one more time?

**Comment by gotagautier** [comment]
I just test it. It works perfect! You can save to IGTV an exit the live without problems. Thanks a lot!

**Comment by harrypython** [comment]
@gotagautier thanks for your help
