### ISSUE TITLE
Error "choose a challenge name"

### ISSUE THREAD

**Issue by gotagautier** [harrypython/itsagramlive#44]
Hi ! Im trying yo use but it appear an error code. When it say "choose a challenge mode" . I press the two options but its the same error

C:\Users\gotag>C:\Users\gotag\AppData\Local\Programs\Python\Python39\IG\test.py
Let's do it!
You'r logged in
Choose a challenge mode (0 - SMS, 1 - Email): 1
Traceback (most recent call last):
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\IG\test.py", line 10, in <module>
    live.start()
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 253, in start
    if self.create_broadcast():
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 410, in create_broadcast
    if self.send_request(endpoint='live/create/', post=self.generate_signature(data)):
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 217, in send_request
    self.get_code_challenge_required(path, choice)
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 125, in get_code_challenge_required
    '_csrftoken': self.LastResponse.cookies['csrftoken']}
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

C:\Users\gotag>C:\Users\gotag\AppData\Local\Programs\Python\Python39\IG\test.py
Let's do it!
You'r logged in
Choose a challenge mode (0 - SMS, 1 - Email): 0
Traceback (most recent call last):
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\IG\test.py", line 10, in <module>
    live.start()
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 253, in start
    if self.create_broadcast():
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 410, in create_broadcast
    if self.send_request(endpoint='live/create/', post=self.generate_signature(data)):
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 217, in send_request
    self.get_code_challenge_required(path, choice)
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 125, in get_code_challenge_required
    '_csrftoken': self.LastResponse.cookies['csrftoken']}
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\gotag\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

C:\Users\gotag>

**Comment by gotagautier** [comment]
any news? or how can i help you?

**Comment by gotagautier** [comment]
nothing? :(

**Comment by whatbeato** [comment]
Yeah bro, Good luck trying to get support here... This program is literally dead.
